### ISSUE TITLE
leak in DatabaseControloer

### ISSUE THREAD

**Issue by steelbytes** [sendbird/sendbird-syncmanager-android#3]
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at android.database.CursorWindow.finalize(CursorWindow.java:179)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at android.database.CursorWindow.<init>(CursorWindow.java:143)
        at android.database.CursorWindow.<init>(CursorWindow.java:120)
        at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
        at com.sendbird.syncmanager.DatabaseController$14.run(DatabaseController.java:706)
        at java.lang.Thread.run(Thread.java:919)

**Comment by steelbytes** [comment]
@sf-nathan-park

**Comment by steelbytes** [comment]
@hoon-sung please can I get a fix

**Comment by steelbytes** [comment]
so although we pay for this we don't get support?
